print("===================================")
print("      PERSONAL INTRODUCTION")
print("===================================")

name = input("Enter your name: ")
age = input("Enter your age: ")
city = input("Enter your city: ")
college = input("Enter your college: ")
course = input("enter your course: ")

print("\n------ Your Information ------")
print("Name :", name)
print("Age :", age)
print("City :", city)
print("College :", college)
print("Course :",course)
